#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <gmp.h>
#include "num.h"
#include "dlog.h"
#include "const.h"
#include "mem.h"

const unsigned int BLOCK_BUFFER_SIZE = 1024;
int str_init_readline(char** pbuffer)
{
    char c = 's';
    int buffer_size = BLOCK_BUFFER_SIZE;
    int str_len = 0;
    (*pbuffer) = (char*) malloc_exit_when_null(buffer_size);

    ssize_t nbytes_read;
    while (c != '\0') {
        // Read character
        nbytes_read = read(STDIN_FILENO, &c, 1);
        if (!nbytes_read || c == '\n' || c == '\0')
            c = '\0';
        else if (c < '0' || c > '9')
            continue;

        // Reallocate if needed
        if (str_len == buffer_size) {
            buffer_size += BLOCK_BUFFER_SIZE;
            (*pbuffer) = (char*) realloc(*pbuffer, buffer_size);
        }

        (*pbuffer)[str_len++] = c;
    }

    return str_len;
}

unsigned int get_number_of_threads(int argc, char** argv)
{   
    long int NUM_THREADS = DEFAULT_NUM_THREADS;
    if (argc >= 2) {
        NUM_THREADS = strtol(argv[1], NULL, 10);
        if (NUM_THREADS == 0 || NUM_THREADS == LONG_MAX || NUM_THREADS == LONG_MIN)
            NUM_THREADS = DEFAULT_NUM_THREADS;
        else
            NUM_THREADS = abs(NUM_THREADS);
    }
    return (unsigned int) NUM_THREADS;
}

size_t get_mem_limit(int argc, char** argv)
{   
    size_t MEM_LIMIT = DEFAULT_MEM_LIMIT;
    if (argc >= 3) {
        char* unit = NULL;
        double MEM_LIMIT_PER_UNIT = strtod(argv[2], &unit);

        if (MEM_LIMIT_PER_UNIT == 0) {
            MEM_LIMIT = DEFAULT_MEM_LIMIT;
        }
        else if ((*unit) == 'M') {
            if (SIZE_MAX / (1024 * 1024) < MEM_LIMIT_PER_UNIT)
                MEM_LIMIT = DEFAULT_MEM_LIMIT;
            else
                MEM_LIMIT = (size_t) (MEM_LIMIT_PER_UNIT * 1024 * 1024);
        }
        else if ((*unit) == 'G' || (*unit) == 0) {
            if (SIZE_MAX / (1024 * 1024 * 1024) < MEM_LIMIT_PER_UNIT)
                MEM_LIMIT = DEFAULT_MEM_LIMIT;
            else
                MEM_LIMIT = (size_t) (MEM_LIMIT_PER_UNIT * 1024 * 1024) * 1024;
        }
        else {
            MEM_LIMIT = DEFAULT_MEM_LIMIT;
        }
    }
    return MEM_LIMIT;
}

void main(int argc, char** argv)
{
    // Get value from arguments.
    unsigned int NUM_THREADS = get_number_of_threads(argc, argv);
    size_t       MEM_LIMIT   = get_mem_limit(argc, argv);

    // Parse curve values from stdin.
    char* p_str;        // field
    char* G_str;        // g
    char* kG_str;       // g^k mod p
    char* n_str;        // order of multiplicative group generated by g.

    str_init_readline(&p_str);
    str_init_readline(&G_str);
    str_init_readline(&kG_str);
    str_init_readline(&n_str);

    // str -> mpz_t
    mpz_t p;
    mpz_init_set_str(p, p_str, 10);
    mpz_t G;
    mpz_init_set_str(G, G_str, 10);
    mpz_t kG;
    mpz_init_set_str(kG, kG_str, 10);
    mpz_t n;
    mpz_init_set_str(n, n_str, 10);

    // dlog() start.
    mpz_t k;
    mpz_init(k);
    if (dlog(p, k, G, kG, n, NUM_THREADS, MEM_LIMIT) == DLOG_SUCCESS) {
        mpz_out_str(stdout, 10, k);
        printf("\n");
    }
    else {
        printf("None\n");
    }

    // cleanup.
    mpz_clear(k);
    mpz_clear(n);
    mpz_clear(kG);
    mpz_clear(G);
    mpz_clear(p);

    free(p_str);
    free(G_str);
    free(kG_str);
    free(n_str);
}