name: Building lib*dlog.so files

on:
  push:
    branches: 
      - "pollard-rho"
      - "pollard-rho-Fp"
      - "baby"
      - "baby-Fp"
      - "pohlig-hellman"

permissions:
  content: write

jobs:
  libbuild:
    name: Building .so files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo $GITHUB_HEAD_REF