name: Building lib*dlog.so files

on:
  push:
    branches: 
      - "pollard-rho"
      - "pollard-rho-Fp"
      - "baby"
      - "baby-Fp"
      - "pohlig-hellman"

permissions:
  contents: write

jobs:
  libbuild:
    name: Building .so files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: pollard-rho
          path: |
            src
            Makefile

      - run: ls -la
      - run: ls -la run
      - run: ls -la Makefile

      - name: Install libgmp && libxxhash
        run: sudo apt-get install libgmp-dev libxxhash-dev

      - name: Building libdlog for E(Fp)
        run: make libdlogefp

      - name: Pusing libdlog for E(Fp) to this branch
        run: |
          cp so/libdlogefp.so libdlogefp.so
          git config --global user.email "hi_im_mistsu_hehe@gmail.com"
          git config --global user.name "Misuru"
          git add libdlogefp.so
          git commit -m "Automatically compile libdlogefp.so"
          git push